debug

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -35,11 +35,23 @@ jobs:
       env:
         TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
 
-    - name: Set ECR repository URL as environment variable
+    - name: Debug Terraform Output
+      run: terraform output ecr_repository_url
+
+    - name: Get ECR Repository URL
       id: ecr_url
       run: |
-        ECR_URL=$(terraform output -raw ecr_repository_url)
-        echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
+        URL=$(terraform output -raw ecr_repository_url || echo "ERROR")
+        echo "DEBUG: ECR_URL=${URL}" # Esto muestra el valor para depuración
+        if [ "${URL}" == "ERROR" ]; then
+          echo "Failed to fetch ECR URL"
+          exit 1
+        fi
+        echo "ECR_URL=${URL}" >> $GITHUB_ENV
+    
+    - name: Terraform State Debug
+      run: terraform state show module.ecr
+      
 
     - name: Checkout repository
       uses: actions/checkout@v2
